In [334]:
import numpy as np
#from numpy import *

# 2D 
# 3D
# concate cols to make array
# set one col of a 3d array to zero
# value to index, index to value
#One can convert the raw data in an array to a binary string (i.e., not in human-readable form) using the tostring 
#function. The fromstring function then allows an array to be created from this data later on. These routines are 
#sometimes convenient for saving large amount of array data in files that can be read later on:

# slicing masking

# set multiple array indices to certain value

# np.where

## Numpy arrays
Arrays are similar to lists in Python, except that every element of an array must be of the same type, typically a numeric type like float or int. Array operations are more efficient than list operations.

In [335]:
arr = np.array([1, 3, 8, 6])   # numeric data type is not specified. output is an intiger array.
arr

array([1, 3, 8, 6])

In [336]:
print(type(arr))
print(type(arr[0]))

<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [337]:
arr_int = np.array([1, 3, 8, 6], int)   # numeric data type is specified to be int
arr_int

array([1, 3, 8, 6])

In [338]:
print(type(arr_int[0]))

<class 'numpy.int64'>


In [339]:
arr_float = np.array([1, 3, 8, 6], float)   # numeric data type is specified to be float
arr_float 

array([ 1.,  3.,  8.,  6.])

In [340]:
print(type(arr_float[0]))

<class 'numpy.float64'>


In [341]:
# convert data type. from int to array
arr = np.array([1, 3, 8, 6])  
print(arr)
arr = np.array(arr, float)
print(arr)

[1 3 8 6]
[ 1.  3.  8.  6.]


## Multidimensional arrays and matrices

In [342]:
# A 2D array or a matrix
row1 = range(0,5)
row2 = range(5,10)
row3 = range(10, 15)

mult_arr = np.array( (row1, row2, row3), float)
mult_arr

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.]])

#### Array elements and indices | slicing and masking

In [343]:
# accessing value given indices
mult_arr[2,0]  #access the first entry of the third row

10.0

In [344]:
# the in function can be used to see is a value exists in a array
if 10 in mult_arr:
    print(True)

True


In [345]:
# get indices given entry of an array
i,j = np.where(mult_arr==10)
i, j

(array([2]), array([0]))

In [346]:
mult_arr[i,j] = mult_arr[i,j]*2
mult_arr

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 20.,  11.,  12.,  13.,  14.]])

In [347]:
mult_arr[-1,-1] = np.nan
mult_arr

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 20.,  11.,  12.,  13.,  nan]])

In [348]:
# (re)fill a row with the same value by specifying a list
mult_arr[0, :] = [0]*5
mult_arr

array([[  0.,   0.,   0.,   0.,   0.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 20.,  11.,  12.,  13.,  nan]])

In [349]:
# (re)fill a row with the same value using the fill funtion. The argument of fill must be scalar
mult_arr[0,:].fill(5)
mult_arr

array([[  5.,   5.,   5.,   5.,   5.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 20.,  11.,  12.,  13.,  nan]])

In [350]:
# (re)fill a column with a list
mult_arr[:,1] = [3, 5, 6]
mult_arr

array([[  5.,   3.,   5.,   5.,   5.],
       [  5.,   5.,   7.,   8.,   9.],
       [ 20.,   6.,  12.,  13.,  nan]])

In [351]:
# the first (0-th) column of the array
col1 = mult_arr[:,0]  
print(col1, type(col1), len(col1), sum(col1))

[  5.   5.  20.] <class 'numpy.ndarray'> 3 30.0


In [352]:
# the last column of the array
last_col = mult_arr[:,-1]  
print(last_col, type(last_col), len(last_col), sum(last_col))

[  5.   9.  nan] <class 'numpy.ndarray'> 3 nan


In [353]:
mult_arr[0:2, 0:2] = 99
mult_arr

array([[ 99.,  99.,   5.,   5.,   5.],
       [ 99.,  99.,   7.,   8.,   9.],
       [ 20.,   6.,  12.,  13.,  nan]])

In [354]:
mult_arr[0:2, 2:4].fill(99)
mult_arr

array([[ 99.,  99.,  99.,  99.,   5.],
       [ 99.,  99.,  99.,  99.,   9.],
       [ 20.,   6.,  12.,  13.,  nan]])

In [355]:
ind = np.argwhere(mult_arr==99)
ind

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3]])

In [356]:
ind_nan = np.argwhere(np.isnan(mult_arr))
ind_nan

array([[2, 4]])

### Array size, shape and dimension

In [357]:
mult_arr[ind] = 999

IndexError: index 3 is out of bounds for axis 0 with size 3

In [358]:
arr2d = np.array(([2, 3, 4, 5.0], [6, 3, 0.5, 3], [3, 4, 5, 6.66]), float)
arr2d

array([[ 2.  ,  3.  ,  4.  ,  5.  ],
       [ 6.  ,  3.  ,  0.5 ,  3.  ],
       [ 3.  ,  4.  ,  5.  ,  6.66]])

In [359]:
# the size of the array (height, width)
arr2d.shape

(3, 4)

In [360]:
# dimension of the array
arr2d.ndim

2

In [361]:
arr3d = np.zeros((3,4,5))
arr3d

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [362]:
a2 = np.array(([1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]), int)
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [363]:
a3 = a2.reshape(3, 2, 2)
a3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [364]:
a3.ndim

3

In [365]:
# the number of array elements
a3.size

12

### Contatenation, stacking, tiling

In [366]:
# concatenate 1D columns to form a 2D matrix
c1 = [1, 11, 111]
c2 = [2, 22, 222]
c3 = [3, 33, 333]

C = np.column_stack( (c1, c2, c3) )
C

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [367]:
# concatenate 1D rows to form a 2D matrix
r1 = [1, 11, 111]
r2 = [2, 22, 222]
r3 = [3, 33, 333]

R = np.row_stack((r1, r2, r3))
R

array([[  1,  11, 111],
       [  2,  22, 222],
       [  3,  33, 333]])

In [368]:
A = np.concatenate( (C, C), axis = 0)
A

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333],
       [  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [369]:
A.shape

(6, 3)

In [370]:
#np.tile(array, (num_times along height, num_times along width) )
A_tiled = np.tile(C, (2, 2))
A_tiled

array([[  1,   2,   3,   1,   2,   3],
       [ 11,  22,  33,  11,  22,  33],
       [111, 222, 333, 111, 222, 333],
       [  1,   2,   3,   1,   2,   3],
       [ 11,  22,  33,  11,  22,  33],
       [111, 222, 333, 111, 222, 333]])

In [371]:
A_tiled.shape

(6, 6)

In [372]:
#np.tile(array, (num_times along depth, num_times along height, num_times along width) )
A_tiled = np.tile(C, (3, 2, 2))
A_tiled

array([[[  1,   2,   3,   1,   2,   3],
        [ 11,  22,  33,  11,  22,  33],
        [111, 222, 333, 111, 222, 333],
        [  1,   2,   3,   1,   2,   3],
        [ 11,  22,  33,  11,  22,  33],
        [111, 222, 333, 111, 222, 333]],

       [[  1,   2,   3,   1,   2,   3],
        [ 11,  22,  33,  11,  22,  33],
        [111, 222, 333, 111, 222, 333],
        [  1,   2,   3,   1,   2,   3],
        [ 11,  22,  33,  11,  22,  33],
        [111, 222, 333, 111, 222, 333]],

       [[  1,   2,   3,   1,   2,   3],
        [ 11,  22,  33,  11,  22,  33],
        [111, 222, 333, 111, 222, 333],
        [  1,   2,   3,   1,   2,   3],
        [ 11,  22,  33,  11,  22,  33],
        [111, 222, 333, 111, 222, 333]]])

In [373]:
A_tiled.shape

(3, 6, 6)

In [374]:
# flatten
# transpose
# newaxis

### Other ways to create arrays/matrices
#### arange, zeros, ones, indentity, eye

In [375]:
# arrange works with range (list) and converts to array
a1 = np.arange(5, dtype=int)
a1

array([0, 1, 2, 3, 4])

In [376]:
a3 = np.arange(9, dtype=int)
a3 = a3.reshape(3,3)
a3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [377]:
all_zero = np.zeros(shape=(10,10), dtype=float)
all_zero 

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [378]:
all_one = np.ones(shape=(10,10), dtype=int)
all_one

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [379]:
# identity matrix
I = np.identity(5, dtype=int)
I

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [380]:
# diagonal matrix along k diagonal
D = np.eye(4, k=2, dtype=float)
D

array([[ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

## Calculations with numerical arrays

#### elementwise mathematical operations

In [381]:
# Numpy arrays are useful for elementwise operations
arr_x = np.array([1, 2, 3, 4])
arr_x = arr_x*2
arr_x

array([2, 4, 6, 8])

In [382]:
arr_y = np.array([5, 6, 7, 8])
arr_y = arr_y**2
arr_y

array([25, 36, 49, 64])

In [383]:
# compare list and array operation
x = [10, 9, 8, 7]
y = [2, 2, 2, 2]
x_plus_y = x + y
x_plus_y

[10, 9, 8, 7, 2, 2, 2, 2]

In [384]:
arr_x = np.array([10, 9, 8, 7])
arr_y = np.array([2, 2, 2, 2])
x_plus_y = arr_x + arr_y
x_plus_y

array([12, 11, 10,  9])

In [385]:
x_power_y = arr_x**arr_y
x_power_y

array([100,  81,  64,  49])

In [386]:
def f(x):
  return 3*x**2 - 2*x + 7

ax = np.array([1, 2, 3, 4])
p = f(ax)
p

array([ 8, 15, 28, 47])

In [387]:
square_root = np.sqrt(ax)
square_root

array([ 1.        ,  1.41421356,  1.73205081,  2.        ])

In [388]:
cosine =  np.cos(ax)
cosine

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [389]:
grid0 = np.zeros(shape=(100,100), dtype=float)
grid0

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [390]:
grid1 = np.ones(shape=(100,100), dtype=float)
grid1

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       ..., 
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.]])

In [391]:
m = (grid0+10)*(grid1+10**2)
m

array([[ 1010.,  1010.,  1010., ...,  1010.,  1010.,  1010.],
       [ 1010.,  1010.,  1010., ...,  1010.,  1010.,  1010.],
       [ 1010.,  1010.,  1010., ...,  1010.,  1010.,  1010.],
       ..., 
       [ 1010.,  1010.,  1010., ...,  1010.,  1010.,  1010.],
       [ 1010.,  1010.,  1010., ...,  1010.,  1010.,  1010.],
       [ 1010.,  1010.,  1010., ...,  1010.,  1010.,  1010.]])