## Matrix using Numpy

In [146]:
import numpy as np

### A matrix can be created same way as a numpy array. In fact a matrix is a type of numpy array.

In [147]:
M = np.matrix([[1,2,3], [4,5,6], [7,8,9]])
M

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Flip a matrix

In [148]:
# UP-DOWN
A = np.array([[1,1,1], [2,2,2], [3,3,3]])
A


array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [149]:
A_up_down = np.flipud(A)
print(A_up_down)

[[3 3 3]
 [2 2 2]
 [1 1 1]]


In [150]:
# LEFT-RIGHT
A = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
A

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [151]:
A_left_right = np.fliplr(A)
A_left_right

array([[3, 2, 1],
       [3, 2, 1],
       [3, 2, 1]])

### Transpose

In [152]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
A_trans = A.T
A_trans

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Matrix addition and subtraction

In [154]:
X = np.array([[1,1,1], [2,2,2], [3,3,3]])
X

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [155]:
Y = np.array([[4,4,4], [5,5,5], [6,6,6]])
Y

array([[4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

In [156]:
#Component-wise addition

X_plus_Y = X + Y
X_plus_Y

array([[5, 5, 5],
       [7, 7, 7],
       [9, 9, 9]])

In [157]:
#Component-wise subtraction
X_minus_Y = X - Y
X_minus_Y

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [158]:
# scalar addition
X_add = X + 100
X_add

array([[101, 101, 101],
       [102, 102, 102],
       [103, 103, 103]])

In [159]:
# scalar subtraction
X_sub = X_add - 100
X_sub

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

### Matrix Multiplication

#### Scalar multiplication

In [160]:
M = np.array([ [5, 5, 5],[5, 5, 5], [5, 5, 5] ])
M

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [161]:
M_mult = M*5
M_mult

array([[25, 25, 25],
       [25, 25, 25],
       [25, 25, 25]])

### Component-wise multiplication

In [162]:
M = np.array([ [3, 3, 3],[3, 3, 3], [3, 3, 3] ])
M

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [163]:
MM = M * M
MM

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

### Matrix Multiplication

In [164]:
A = np.array([ [5, 5, 5],[5, 5, 5], [5, 5, 5] ])
B = np.array([ [3, 3, 3],[3, 3, 3], [3, 3, 3] ])
print("A = \n", A)
print("B = \n", B)

A = 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
B = 
 [[3 3 3]
 [3 3 3]
 [3 3 3]]


In [165]:
AB = np.dot(A, B)
AB

array([[45, 45, 45],
       [45, 45, 45],
       [45, 45, 45]])

In [166]:
X = np.random.uniform(0, 9, size=(3,4))
X

array([[ 8.25118259,  2.26008903,  6.71672535,  3.1776662 ],
       [ 3.82255414,  2.66956237,  4.72223314,  2.35321973],
       [ 1.50504024,  2.3601773 ,  1.32945253,  3.98533179]])

In [167]:
Y = np.random.randint(0, 9, size=(4,1))
Y

array([[7],
       [6],
       [4],
       [5]])

In [168]:
XY = np.dot(X,Y)
XY

array([[ 114.07404464],
       [  73.4302844 ],
       [  49.94081453]])

### Inverse and pseudo-inverse of a matrix (numpy.linalg.inv)

In [169]:
X = np.random.randint(0, 9, size=(3,3))
X

array([[2, 1, 8],
       [5, 6, 7],
       [4, 5, 8]])

In [170]:
invX = np.linalg.inv(X)
invX

array([[ 0.59090909,  1.45454545, -1.86363636],
       [-0.54545455, -0.72727273,  1.18181818],
       [ 0.04545455, -0.27272727,  0.31818182]])

In [171]:
Y = np.random.randint(0, 9, size=(3,4))
Y

array([[3, 4, 1, 2],
       [5, 0, 3, 0],
       [1, 8, 1, 7]])

In [172]:
pinvY = np.linalg.pinv(Y)
pinvY

array([[ 0.21702128,  0.05319149, -0.0893617 ],
       [ 0.39042553, -0.18617021, -0.08723404],
       [-0.36170213,  0.24468085,  0.14893617],
       [-0.42553191,  0.17021277,  0.23404255]])

### Identity Matrix

In [173]:
I4 = np.eye(4)
I4

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Rules associated with transpose and inverse

In [174]:
# Transpose of AB == transpose of (tranpose of A times transpose of B)
A = np.array([ [1, 1], [2, 2] ])
transA = A.T

B = np.array([ [0, 9], [9, 0] ])
transB = B.T

In [175]:
transAB = np.dot(A,B).T
transAB

array([[ 9, 18],
       [ 9, 18]])

In [176]:
transA_transB = np.dot(B.T, A.T)
transA_transB


array([[ 9, 18],
       [ 9, 18]])

In [177]:
A = np.ones((4, 4), dtype=int) + np.random.randint(1,5, size=(4,4))
A

array([[3, 5, 4, 3],
       [5, 2, 2, 2],
       [5, 4, 3, 3],
       [5, 4, 2, 4]])

In [178]:
invA = np.linalg.inv(A)
I = np.dot(A, invA)
I

array([[  1.00000000e+00,  -2.22044605e-16,  -2.22044605e-15,
          0.00000000e+00],
       [ -4.44089210e-16,   1.00000000e+00,  -8.88178420e-16,
          0.00000000e+00],
       [ -4.44089210e-16,  -2.22044605e-16,   1.00000000e+00,
         -4.44089210e-16],
       [  0.00000000e+00,   8.88178420e-16,  -3.55271368e-15,
          1.00000000e+00]])

### Diagonal matrix

In [184]:
# given a row or column vectory diagonalize a matrix
diag_vector = [123, 231, 312]

In [185]:
diagonalMatrix  = np.diag(diag_vector)
diagonalMatrix

array([[123,   0,   0],
       [  0, 231,   0],
       [  0,   0, 312]])

In [192]:
D = np.diag((2,2), k=3)
D

array([[0, 0, 0, 2, 0],
       [0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### Determinant, Eigenvalues and Trace

In [194]:
A = np.random.randint(0, 9, size=(3,3))
A

array([[0, 2, 2],
       [5, 4, 6],
       [1, 3, 6]])

In [195]:
detA = np.linalg.det(A)
detA

-26.000000000000004

In [196]:
eigen_value, eigen_vector = np.linalg.eig(A)
print(eigen_value)
print(eigen_vector)

[ 10.33711451  -1.76343036   1.42631585]
[[-0.26188248 -0.61721126 -0.28497098]
 [-0.76442023  0.75737074 -0.77174168]
 [-0.58913435 -0.2131662   0.56851237]]


In [197]:
traceA = np.trace(A)
traceA

10

In [198]:
traceA = sum(eigen_value)
traceA

9.9999999999999964

### Thresholding (binarization)

In [199]:
M = np.matrix([ [2, 2, 2], [3, 3,3], [4, 4, 4] ])
M

matrix([[2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])

In [200]:
binM = np.where(M==3, 0, 1)
binM

array([[1, 1, 1],
       [0, 0, 0],
       [1, 1, 1]])

In [202]:
threshM = np.where(M<3, -1, 111)
threshM

array([[ -1,  -1,  -1],
       [111, 111, 111],
       [111, 111, 111]])

In [203]:
replaceM = np.where(M==2, M, 5) #keep entries==2, replace other entries
replaceM

array([[2, 2, 2],
       [5, 5, 5],
       [5, 5, 5]])

### Rotation

# ????