### Matrix 

In [11]:
import numpy as np

mat = np.matrix('1 2; 3 4')
mat

matrix([[1, 2],
        [3, 4]])

In [14]:
row1 = [1, 2, 3]
row2 = [4, 5, 6]
row3 = [7, 8, 9]

mat  = np.array([row1, row2, row3] )
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
row1 = [1, 2, 3]
row2 = [4, 5, 6]
row3 = [7, 8, 9]

mat  = np.matrix([row1, row2, row3] )
mat

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Matrix arithmatic

In [16]:
A = np.matrix([[1, 1, 1],
               [2, 2, 2],
               [3, 3, 3]])

B = np.matrix([[1, 1, 1],
               [1, 1, 1],
               [1, 1, 1]])

print(A+B)

[[2 2 2]
 [3 3 3]
 [4 4 4]]


### Element-wise multiplication
* Must be an array, not matrix

In [25]:
A = np.array([[1, 1, 1],
               [2, 2, 2],
               [3, 3, 3]])

B = A

print(A)
print(B)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [26]:
print(A*B)

[[1 1 1]
 [4 4 4]
 [9 9 9]]


In [ ]:
### Matrix multiplication

In [28]:
A = np.array([[1, 1, 1],
               [2, 2, 2],
               [3, 3, 3]])

B = A

print(np.dot(A,B))

[[ 6  6  6]
 [12 12 12]
 [18 18 18]]


#### Matrix multiplication of A and B 
* when A and B are defined as matrices

In [29]:
A = np.matrix([[1, 1, 1],
               [2, 2, 2],
               [3, 3, 3]])

B = A

print(A)
print(B)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [30]:
print(A*B)

[[ 6  6  6]
 [12 12 12]
 [18 18 18]]


### Size and Dimension of a matrix

In [33]:
row1 = list(range(0, 10, 2))
row2 = list(range(11, 20, 2))
row3 = list(range(21, 30, 2))

A = np.array([row1, row2, row3])
print(A)

[[ 0  2  4  6  8]
 [11 13 15 17 19]
 [21 23 25 27 29]]


#### number of elements in A

In [39]:
np.size(A)

15

In [40]:
A.size

15

#### dimension of A: (height, width)

In [42]:
np.shape(A)

(3, 5)

In [43]:
A.shape

(3, 5)

### Reshaping

In [45]:
A.reshape(5, 3)

array([[ 0,  2,  4],
       [ 6,  8, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

### Determinant
* for square matrices only

#### Example 1

In [54]:
A = np.array([[2, 5], [3, 1]])

from numpy import linalg as alg
detA = alg.det(A)
print(detA)

-13.0


In [55]:
row1 = np.random.randint(1, 11, 3)
row2 = np.random.randint(2, 22, 3)
row3 = np.random.randint(3, 33, 3)

In [56]:
M = np.array([row1, row2, row3])
M

array([[ 2,  7,  3],
       [10,  7,  6],
       [31,  6, 12]])

In [57]:
from numpy import linalg as alg

detM = alg.det(M)
print(detM)

87.0


### Inverse of a matrix

#### A matrix is not invertible in it's determinant is zero

* inverse

In [60]:
from numpy import linalg as alg

A = np.array([[6, 2], [1, 5]])
invA = alg.inv(A)
print(invA)

[[ 0.17857143 -0.07142857]
 [-0.03571429  0.21428571]]


* pseudo-inverse

In [61]:
A = np.array([[6, 2], [1, 5]])
pinvA = alg.pinv(A)
print(pinvA)

[[ 0.17857143 -0.07142857]
 [-0.03571429  0.21428571]]


### Trace of a matrix

In [66]:
from numpy import linalg as alg

M = np.array([[6, 2], [1, 5]])
print(M
     )
traceM = np.trace(M)
print(traceM)


[[6 2]
 [1 5]]
11


#### diagonal element of a matrix

In [70]:
print(np.diag(M))

[6 5]


### Idenity matrix

In [73]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [74]:
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [75]:
np.eye(5, dtype=float)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

#### A matrix multiplied with its inverse gives an identity matri 

In [85]:
X = np.array([[6, 2], [1, 5]])
invX = np.linalg.inv(X)

X_invX = (np.dot(X, invX))
print( np.round(X_invX, 2) )


invX_X = (np.dot(invX, X))
print( np.round(invX_X, 2) )

[[ 1.  0.]
 [ 0.  1.]]
[[ 1.  0.]
 [ 0.  1.]]


### Orthonormal matrix

* A matrix X is orthonormal if transpose(X) == inverse(X)

### Matrix Transformation 

### Rotation matrix

In [98]:
from math import *

# theta in degree
theta = 30 

# theta in radian
theta = (theta*pi)/180  # radian


R = np.array([ [cos(theta), -sin(theta)], 
               [sin(theta), cos(theta)] ])

print(R)

[[ 0.8660254 -0.5      ]
 [ 0.5        0.8660254]]


### Eigenvectors
* eigen vector
* eigen value
* eigen energy
* geometric interpretation

In [1]:
import numpy as np
from numpy import linalg as alg

#### Example 1

In [2]:
A = [ [2, -4],
      [-1, -1] ]

A = np.array(A)

In [3]:
val, vec = alg.eig(A)

In [4]:
val

array([ 3., -2.])

In [5]:
vec

array([[ 0.9701425 ,  0.70710678],
       [-0.24253563,  0.70710678]])

In [6]:
vec_trans = np.transpose(vec)
vec_trans

array([[ 0.9701425 , -0.24253563],
       [ 0.70710678,  0.70710678]])

In [8]:
v1 = vec_trans[0]/min(vec_trans[0])
v1

array([-4.,  1.])

In [9]:
v2 = vec_trans[1]/min(vec_trans[1])
v2

array([ 1.,  1.])

#### Example 2

In [10]:
A = [ [1, 1, 1],
      [1, -1, 1],
      [2, 2, 2]]

A = np.array(A)

In [11]:
val, vec = alg.eig(A)

In [12]:
val

array([  3.64575131e+00,  -3.20923843e-17,  -1.64575131e+00])

In [13]:
vec

array([[ -4.29655912e-01,  -7.07106781e-01,   1.93953652e-01],
       [ -2.77450869e-01,  -1.35042819e-16,  -9.01060433e-01],
       [ -8.59311825e-01,   7.07106781e-01,   3.87907304e-01]])

In [14]:
set(val)

{-1.6457513110645905, -3.2092384305570931e-17, 3.6457513110645885}