## Random Numbers

### Using random module

In [69]:
import random

#### Generate a single random integer between two numbers, n_min and n_max. Note n_max is included.

In [70]:
n_min = 2
n_max = 10
random.randint(n_min, n_max)

2

#### Generate n random numbers within a range, where n >= 1.

In [71]:
random.sample(range(0, 10), 3)

[9, 5, 8]

#### Draw n numbers randomly from a list of numbers

In [72]:
list_of_numbers = [5, 2, 5, 6, 3, 1, 50, 3, 45, 11]
random.sample(list_of_numbers, 3)

[2, 3, 3]

#### NB: Random sampling works for any list elements

In [73]:
list_of_elements = [5.0, 2.1, 5.6, 6.5, 3.5, 1.11, 50.99, 3.98, 45.5, 11.121]
random.sample(list_of_elements, 3)

[1.11, 45.5, 3.5]

In [74]:
list_of_elements = ['a', 'b', 'c', 6.5, 3.5, 1.11, 50.99, 3.98, 45.5, 11.121]
random.sample(list_of_elements, 3)

['b', 3.98, 3.5]

#### Generate a single float between 0, 1. 

In [78]:
random.random()

0.11654884124895937

#### ??? How to generate more than one random float?

### Choice

#### Draw a single element from a sequence.

In [79]:
random.choice(['yes', 'no', 'may be'])      

'yes'

### Shuffle

#### Shuffle elements in a list

In [80]:
deck = 'two three four five six seven eight nine ten jack queen king ace'.split()
random.shuffle(deck) 
deck

['ace',
 'queen',
 'six',
 'nine',
 'eight',
 'king',
 'two',
 'four',
 'ten',
 'jack',
 'seven',
 'five',
 'three']

### Seed

In [124]:
random.seed(101)
x = random.randint(0, 100)
xx = random.randint(0, 100)
random.seed()
y = random.randint(0, 100)
yy = random.randint(0, 100)
x, xx, y, yy

(74, 24, 17, 23)

In [112]:
random.seed(3)
random.sample(range(0,100), 5)

[30, 75, 69, 16, 47]

## Numpy

In [ ]:
import numpy as np

In [55]:
# generate n random numbers within a range or list. with or without replacement
np.random.choice([1, 5, 6, 7, 2, 3, 3], 4, replace=True)

array([7, 3, 7, 3])

In [56]:
# generate n random numbers within a range or list. with or without replacement
np.random.choice([1, 5, 6, 7, 2, 3, 3], 4, replace=False)

array([3, 6, 1, 5])

In [60]:
np.random.choice(range(1, 100), 4, replace=False)

array([95, 89, 26, 38])

#### Random integer with randint

In [61]:
# random integer between min, max and size=(h, w)
np.random.randint(3, 7, size=(4,4))

array([[4, 5, 4, 5],
       [5, 5, 5, 4],
       [5, 6, 4, 3],
       [6, 3, 6, 5]])

#### random uniform float with random.uniform

In [64]:
# random float between min, max and size=(h, w)
np.random.uniform(3, 7, size=(3,4))

array([[ 6.52097172,  4.8005387 ,  6.16118542,  3.41806407],
       [ 4.77926414,  5.08912979,  5.25845203,  6.50085605],
       [ 5.75707198,  3.73662375,  6.62251373,  6.28696939]])

#### Shuffle

In [86]:
arr = np.random.randint(1, 10, size=(1, 7))
arr

array([[6, 6, 1, 2, 3, 5, 6]])

In [90]:
a = list(arr[0,:])
a

[6, 6, 1, 2, 3, 5, 6]

In [92]:
np.random.shuffle(a)
a

[3, 1, 6, 6, 6, 5, 2]