In [7]:
import numpy as np
import math

#### Define a 1D vector

In [8]:
v = np.array([3, 2, 5])
print(v)

[3 2 5]


### Norm of a vector

#### 2-norm of vector v

In [10]:
v = np.array([3, 2, 5])
norm2 = math.sqrt(sum(v**2))
print(norm2)

6.164414002968976


#### p-norm of vector v

In [14]:
p = 4
v = np.array([3, 2, 5])
norm_p = ( sum(v**p) ) **(1/p)
print(norm_p)

5.18363363724


#### Compute norm using Numpy Linear Algebra package

In [18]:
from numpy import linalg as alg

v = np.array([3, 2, 5])
norm2 = alg.norm(v)  # 2-nor is default
print(norm2)

6.16441400297


In [19]:
from numpy import linalg as alg

v = np.array([3, 2, 5])
norm4 = alg.norm(v, 4)
print(norm4)

5.18363363724


### Vector Arithmatic

In [20]:
u = np.array([1, 2, 3])
v = np.array([3, 2, 5])

#### vector addition

In [21]:
u_plus_v = u+v
print(u+v)

[4 4 8]


#### vector subtraction

In [22]:
u_minus_v = u-v
print(u-v)

[-2  0 -2]


#### vector scaling

In [23]:
a = 21
au = a*u
av = a*v
print(au, av)

[21 42 63] [ 63  42 105]


### Inner (dot) product

* transpose

In [37]:
# a <dot> b = sum of ( (transpose of a) \times b )

import numpy as np

a = np.array([6, 2, -3])
b = np.array([4, 1, 5])

inner_product = sum(np.transpose(a) * b)
inner_product

[ 6  2 -3]


11

* np.dot and np.inner

In [29]:
import numpy as np

a = np.array([6, 2, -3])
b = np.array([4, 1, 5])

inner_product = np.inner(a,b)
print("Inner product:", inner_product)

dot_product = np.dot(a,b)
print("\nDot product:", dot_product)

print("\nSame thing, call it a dot product or an inner product")

Inner product: 11

Dot product: 11

Same thing, call it a dot product or an inner product


### Cross product

In [43]:
import numpy as np

a = np.array([6, 2, -3])
b = np.array([4, 1, 5])

In [44]:
np.cross(a, b)


array([ 13, -42,  -2])

In [45]:
np.cross(b, a)

array([-13,  42,   2])